spring:
  cloud:
    stream:
      binders:
        kafka-plain:
          type: kafka
          environment.spring.cloud.stream.kafka.binder:
            brokers: localhost:9093
            autoAddPartitions: true
            autoCreateTopics: true
            configuration:
              security.protocol: SSL
              ssl.enabled.protocols: TLSv1.2
              ssl.truststore.type: JKS
              ssl.truststore.location: /Users/pratya.yeekhaday/Desktop/Workshop/SpringBoot-Cloud-Kafka-SSL/secrets/broker.truststore.jks
              ssl.truststore.password: datahub
      bindings:
        customerConsumer:
          binder: kafka-plain
          group: Customer.Group
          destination: topic.customer
        customerProducer:
          binder: kafka-plain
          destination: topic.customer

